# Generated by Django 3.1.7 on 2021-03-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currentstage', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('A1', models.TextField()),
                ('A2', models.TextField(blank=True, null=True)),
                ('A3', models.TextField(blank=True, null=True)),
                ('A4', models.TextField(blank=True, null=True)),
                ('A5', models.TextField(blank=True, null=True)),
                ('A6', models.TextField(blank=True, null=True)),
                ('E1', models.IntegerField(blank=True, null=True)),
                ('E2', models.IntegerField(blank=True, null=True)),
                ('E3', models.IntegerField(blank=True, null=True)),
                ('E4', models.IntegerField(blank=True, null=True)),
                ('E5', models.IntegerField(blank=True, null=True)),
                ('E6', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
